#pragma once

#include <functional>
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <limits>
#include <unistd.h>
#include <cassert>
#include <iostream>
#include <iomanip>
#include <vector>
#include <numeric>
#include <string>
#include <iterator>
#include <fstream>
#include <random>
#include <initializer_list>